lab3/lab3/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.urls import path, include

from lab3 import settings
from people.views import UserTypeRedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('', UserTypeRedirectView.as_view(), name='user_type'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('mailing/', include('mailing.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab3/people/urls.py
from django.urls import path
from people.views import TeacherListView, TeacherDetailView, StudentDetailView, StudentAccountDetailView, \
    StudentUpdateView, StudentCreateView, TeacherCreateView, TeacherUpdateView

urlpatterns = [
    path('teacher/', TeacherListView.as_view(), name='teacher_list'),
    path('teacher/info/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),
    path('student/add/', StudentCreateView.as_view(), name='student_add'),
    path('student/update/<int:pk>/', StudentUpdateView.as_view(), name='student_update'),
    path('teacher/add/', TeacherCreateView.as_view(), name='teacher_add'),
    path('teacher/update/<int:pk>/', TeacherUpdateView.as_view(), name='teacher_update'),
    path('student/info/<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('student/', StudentAccountDetailView.as_view(), name='student_account'),
    ]

lab3/mailing/models.py
from django.db import models
from django.urls import reverse_lazy

from people.models import User


class Mailing(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название рассылки')
    subject = models.CharField(max_length=150, verbose_name='Заголовок')
    message = models.TextField(verbose_name='Текст сообщения')
    from_user = models.ForeignKey(User, related_name='mailing_from', on_delete=models.CASCADE, verbose_name='Отправитель')
    to_users = models.ManyToManyField(User, related_name='mailing_to', verbose_name='Получатели')
    created = models.DateField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('mailing_detail', kwargs={'pk': self.id})

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

lab3/people/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.urls import reverse_lazy

from lab3.settings import USER_STATUS_CHOICES, GENDER_CHOICES


class User(AbstractUser):
    sex = models.CharField('Пол', choices=GENDER_CHOICES, max_length=1)
    birth_date = models.DateField('Дата рождения', blank=True, null=True)
    photo = models.ImageField(default='diary/static/media/default-user.png', blank=True)
    description = models.TextField('Характеристика')
    user_status = models.CharField('Статус пользователя', choices=USER_STATUS_CHOICES, max_length=15)
    updated = models.DateField('Дата обновления', auto_now=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    objects = UserManager()

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Teacher(models.Model):
    position = models.CharField('Должность', max_length=99)
    group_manager = models.ForeignKey('diary.Group', related_name='teacher', verbose_name='Курирует группу',
                                      on_delete=models.SET_NULL, null=True, blank=True)
    lessons = models.ManyToManyField('diary.Lesson', related_name='teachers', verbose_name='Ведет предметы')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='teacher', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse_lazy('teacher_detail', kwargs={'pk': self.user_id})

    class Meta:
        verbose_name = 'Учитель'
        verbose_name_plural = 'Учителя'


class Student(models.Model):
    group = models.ForeignKey('diary.Group', related_name='students', verbose_name='Состоит в группе',
                              on_delete=models.CASCADE, null=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='student', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse_lazy('student_detail', kwargs={'pk': self.user_id})

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

lab3/people/forms.py
from django import forms
from django.forms import modelformset_factory

from diary.models import Group, Lesson
from .models import Student, User, Teacher


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name',
                  'birth_date', 'sex', 'photo', 'description']
        widgets = {'username': forms.TextInput(attrs={'placeholder': 'Имя пользователя'}),
                   'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
                   'password': forms.PasswordInput(attrs={'placeholder': 'Пароль'}),
                   'first_name': forms.TextInput(attrs={'placeholder': 'Имя'}),
                   'last_name': forms.TextInput(attrs={'placeholder': 'Фамилия'}),
                   'birth_date': forms.DateInput(attrs={'placeholder': 'Дата рождения', 'type': 'date'}),
                   'sex': forms.Select(attrs={'placeholder': 'Пол'}),
                   'photo': forms.FileInput(attrs={'class': 'input-file'}),
                   'description': forms.Textarea(attrs={'placeholder': 'Характеристика', 'rows': 5, 'cols': 30}),
                   }

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'sex', 'birth_date', 'photo', 'description']
        widgets = {'first_name': forms.TextInput(attrs={'placeholder': 'Имя'}),
                   'last_name': forms.TextInput(attrs={'placeholder': 'Фамилия'}),
                   'birth_date': forms.DateInput(attrs={'type': 'date', 'data-date-format': 'yyyy-mm-dd'},
                                                 format=('%Y-%m-%d')),
                   'sex': forms.Select(attrs={'placeholder': 'Пол'}),
                   'photo': forms.FileInput(attrs={'class': 'input-file'}),
                   'description': forms.Textarea(attrs={'placeholder': 'Характеристика', 'rows': 5, 'cols': 40}),
                   }


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('group',)
        widgets = {'group': forms.Select()}


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        group_manager = forms.ModelChoiceField(queryset=Group.objects.all(), to_field_name='number')
        lessons = forms.ModelMultipleChoiceField(queryset=Lesson.objects.all(), to_field_name='name')
        fields = ('group_manager', 'position', 'lessons')
        widgets = {
                   'position': forms.TextInput(attrs={'placeholder': 'Должность'}),
                   }


StudentFormSet = modelformset_factory(Student, form=StudentForm, max_num=1, extra=1)
TeacherFormSet = modelformset_factory(Teacher, form=TeacherForm, max_num=1, extra=1)

lab3/people/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, RedirectView, ListView
from lab3.settings import TEACHER, STUDENT
from .models import Teacher, User, Student
from .permissions import TeacherPermissionsMixin, StudentPermissionsMixin, SuperUserPermissionsMixin
from diary.permissions import ScoreJournalMixin
from diary.models import Lesson, Score
from .forms import UserCreateForm, UserUpdateForm, StudentForm, StudentFormSet, TeacherForm, TeacherFormSet


logger = logging.getLogger('main')


class TeacherListView(LoginRequiredMixin, ListView):
    template_name = 'people/teacher_list.html'

    def get_queryset(self):
        logger.info('Showing list of teachers')
        queryset = User.objects.select_related('teacher__group_manager').filter(user_status=TEACHER)
        return queryset


class TeacherDetailView(LoginRequiredMixin, DetailView):
    model = Teacher
    template_name = 'people/teacher_detail.html'

    def get_queryset(self):
        logger.info('Showing teacher info')
        queryset = User.objects.select_related('teacher__group_manager').filter(user_status=TEACHER)
        return queryset


class StudentDetailView(LoginRequiredMixin, TeacherPermissionsMixin, DetailView):
    template_name = 'people/student_detail.html'

    def get_queryset(self):
        logger.info('Showing student info')
        queryset = User.objects.select_related('student__group').filter(user_status=STUDENT)
        return queryset


class StudentAccountDetailView(LoginRequiredMixin, StudentPermissionsMixin, ScoreJournalMixin, DetailView):
    template_name = 'people/student_account.html'
    context_object_name = 'student'

    def get_object(self, queryset=None):
        logger.info('Showing student account')
        return User.objects.select_related('student').get(pk=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super(StudentAccountDetailView, self).get_context_data(**kwargs)
        date_period = self.create_date_period_list()
        lessons = Lesson.objects.filter(group__students=self.request.user.student.id)
        scores = Score.objects.filter(student_id=self.request.user.pk,
                                      created__in=date_period).values('id', 'lesson_id', 'score', 'created')

        context['date_period'] = date_period
        context['lessons'] = lessons
        context['scores_dict'] = self.create_scores_dict(date_period, scores, lessons, 'lesson_id')
        return context


class StudentCreateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, CreateView):
    form_class = UserCreateForm
    template_name = 'people/student_create.html'
    success_url = reverse_lazy('student_add')
    success_message = 'Ученик успешно добавлен.'

    def get_context_data(self, **kwargs):
        data = super(StudentCreateView, self).get_context_data(**kwargs)
        data['student_form'] = StudentForm()
        return data

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        student_form = StudentForm(self.request.POST)
        if form.is_valid() and student_form.is_valid():
            logger.info('New student created')
            user = form.save(commit=False)
            user.user_status = STUDENT
            student = student_form.save(commit=False)
            student.user = user
            user.save()
            student.save()
            return self.form_valid(form)
        else:
            logger.info('Student created form was fill incorrectly')
            return self.render_to_response({'form': form, 'student_form': student_form})


class StudentUpdateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, UpdateView):
    model = User
    queryset = User.objects.filter(user_status=STUDENT)
    form_class = UserUpdateForm
    template_name = 'people/student_update.html'
    success_message = 'Данные ученика успешно обновлены.'

    def post(self, request, *args, **kwargs):
        form = UserUpdateForm(self.request.POST)
        student_formset = StudentFormSet(self.request.POST, prefix='student')
        if student_formset.is_valid():
            logger.info('Student info was updated')
            student_formset.save()
            return super(StudentUpdateView, self).post(self.request.POST)

        else:
            logger.info('Updating student form was filled incorrectly')
            return self.render_to_response(
                {'form': form, 'student_form': student_formset}
            )

    def get_context_data(self, **kwargs):
        data = super(StudentUpdateView, self).get_context_data(**kwargs)
        student_formset = StudentFormSet(queryset=Student.objects.filter(user_id=self.kwargs['pk']), prefix='student')

        data['student_form'] = student_formset
        return data

    def get_success_url(self):
        return reverse_lazy('student_update', kwargs={'pk': self.kwargs['pk']})


class TeacherCreateView(LoginRequiredMixin, SuperUserPermissionsMixin, SuccessMessageMixin, CreateView):
    form_class = UserCreateForm
    template_name = 'people/teacher_create.html'
    success_url = reverse_lazy('teacher_add')
    success_message = 'Преподаватель успешно добавлен.'

    def get_context_data(self, **kwargs):
        data = super(TeacherCreateView, self).get_context_data(**kwargs)
        data['teacher_form'] = TeacherForm()
        return data

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        teacher_form = TeacherForm(self.request.POST)
        if form.is_valid() and teacher_form.is_valid():
            logger.info('New Teacher was created')
            user = form.save(commit=False)
            user.user_status = TEACHER
            teacher = teacher_form.save(commit=False)
            teacher.user = user
            user.save()
            teacher.save()
            return self.form_valid(form)
        else:
            logger.info('Creating teacher form was filled incorrectly')
            return self.render_to_response({'form': form, 'teacher_form': teacher_form})


class TeacherUpdateView(LoginRequiredMixin, SuperUserPermissionsMixin, SuccessMessageMixin, UpdateView):
    model = User
    queryset = User.objects.filter(user_status=TEACHER)
    form_class = UserUpdateForm
    template_name = 'people/teacher_update.html'
    success_message = 'Данные преподавателя успешно обновлены.'

    def post(self, request, *args, **kwargs):
        form = UserUpdateForm(self.request.POST)
        teacher_formset = TeacherFormSet(self.request.POST, prefix='teacher')
        if teacher_formset.is_valid():
            logger.info('Teacher info was updated')
            teacher_formset.save()
            return super(TeacherUpdateView, self).post(self.request.POST)

        else:
            logger.info('Updating teacher form was filled incorrectly')
            return self.render_to_response(
                {'form': form, 'teacher_form': teacher_formset}
            )

    def get_context_data(self, **kwargs):
        data = super(TeacherUpdateView, self).get_context_data(**kwargs)
        teacher_formset = TeacherFormSet(queryset=Teacher.objects.filter(user_id=self.kwargs['pk']), prefix='teacher')

        data['teacher_form'] = teacher_formset
        return data

    def get_success_url(self):
        return reverse_lazy('teacher_update', kwargs={'pk': self.kwargs['pk']})


class UserTypeRedirectView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        logger.info('User was redirected')
        return reverse_lazy('teacher_list')

lab3/people/templates/people/student_account.html
{% extends 'base.html' %}

{% block title %} Личный кабинет {% endblock %}

{% block content %}
    <h1>Оценки</h1>
    <form action="{% url 'student_account' %}" method="get">
        <label> С
            <input class="input-date" name="start-date" type="date" value="{{ date_period|first|date:"Y-m-d" }}" >
        </label>

        <label> по
            <input class="input-date" name="end-date" type="date" value="{{ date_period|last|date:"Y-m-d" }}">
        </label>
        <button class="btn-filter btn-filter-purple" type="submit">Применить</button>
    </form>
    <p></p>

    <table class="table-journal">
        <thead>
            <tr>
                <th>Предметы</th>
                 {% for date in date_period %}
                     <th>{{ date|date:"d.m.Y" }}</th>
                 {% endfor %}
            </tr>
        </thead>

        <tbody>
        {% for lesson in lessons %}
            <tr>
                <td>{{ lesson.name }}</td>
                {% for date in date_period %}
                    {% with score_id_tuple=scores_dict|get_dict_value:date|get_dict_value:lesson.id %}
                        <td>
                            {% if score_id_tuple|get_list_value:0 == 0 %}
                                <span data-scoreid="{{ score_id_tuple|get_list_value:1 }}">--</span>
                            {% else %}
                                <span data-scoreid="{{ score_id_tuple|get_list_value:1 }}">
                                    {{ score_id_tuple|get_list_value:0 }}
                                </span>
                            {% endif %}

                        </td>
                    {% endwith %}
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p></p>
{% endblock %}

lab3/people/templates/people/student_create.html
{% extends 'base.html' %}

{% block title %}Новый ученик{% endblock %}

{% block content %}
    <h1>Новый ученик</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        <div class="create-form">
            {% csrf_token %}
            <div id="left-side">
                <p>
                    {{ form.username }}
                    {{ form.username.errors }}
                </p>

                <p>
                    {{ form.email }}
                    {{ form.email.errors }}
                </p>

                <p>
                    {{ form.password }}
                    {{ form.password.errors }}
                </p>

                <p>
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </p>
                <p>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </p>

                <p>
                    <label for="{{ form.birth_date.id_for_label }}">Дата рождения:</label> <br>
                    {{ form.birth_date }}
                    {{ form.birth_date.errors }}
                </p>

                 <p>
                    <label for="{{ form.sex.id_for_label }}">Пол:</label> <br>
                    {{ form.sex }}
                    {{ form.sex.errors }}
                </p>
            </div>

            <div id="right-side">
                <p>
                    {{ form.description }}
                    {{ form.description.errors }}
                </p>
                <p style="color: #606479; font-size: 14px">Фотография ученика:</p>
                <p>
                    <label class="label-file" for="{{ form.photo.id_for_label }}">Загрузить фото</label> <br>
                    <input type="file" name="photo" class="input-file" accept="image/*" id="id_photo"
                           onchange="document.getElementById('upload-file-info').innerText = this.value;">
                    <br>
                    <span class='label-info' id="upload-file-info"></span>
                    {{ form.photo.errors }}
                </p>
                <p>
                    <label for="{{ student_form.group.id_for_label }}">Студент группы:</label> <br>
                    {{ student_form.group }}
                    {{ student_form.group.errors }}
                </p>
            </div>

            <div id="contact">
                <input type="submit" class="save_button" value="Сохранить">
            </div>

        </div>
    </form>
{% endblock %}

lab3/people/templates/people/student_sidebar.html
{% block sidebar %}
    <h3>Личный кабинет</h3>
    <img class="user-avatar" src="/static/{{ user.photo }}" alt="{{ user.get_full_name }}">
    <p><b>{{ user.get_full_name }}</b></p>
    <ul>
        <li><a href="{% url 'student_account' %}">Мои оценки</a></li>
        <li><a href="{% url 'teacher_list' %}">Преподаватели</a></li>
    </ul>
    <hr>
    <p><b>Настройки:</b></p>
    <ul>
        <li><a href="{% url 'logout' %}">Выйти</a></li>
    </ul>
{% endblock %}

lab3/people/templates/people/student_update.html
{% extends 'base.html' %}

{% block title %}Редактировать студента{% endblock %}

{% block content %}
    <h1>Редактировать студента</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}

     <form action="" method="post" enctype="multipart/form-data">
        <div class="create-form">
            {% csrf_token %}

            <div id="left-side">

               <p>
                    <label for="{{ form.first_name.id_for_label }}">Имя:</label> <br>
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </p>
                <p>
                    <label for="{{ form.last_name.id_for_label }}">Фамилия:</label> <br>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </p>

                <p>
                    <label for="{{ form.birth_date.id_for_label }}">Дата рождения:</label> <br>
                    {{ form.birth_date }}
                    {{ form.birth_date.errors }}
                </p>

                 <p>
                    <label for="{{ form.sex.id_for_label }}">Пол:</label> <br>
                    {{ form.sex }}
                    {{ form.sex.errors }}
                </p>

                {{ student_form.management_form }}
                {{ student_form.as_p }}
            </div>

            <div id="right-side">
                <p>
                    <label for="{{ form.description.id_for_label }}">Характеристика:</label> <br>
                    {{ form.description }}
                    {{ form.description.errors }}
                </p>

                <p style="color: #606479; font-size: 14px">Фотография ученика:</p>
                <p>
                    <img id="avatar" align="left" class="user-avatar-mini" src="/media/{{ form.photo.value }}" alt="">
                    <label class="label-file" for="{{ form.photo.id_for_label }}">Загрузить фото</label> <br>
                    <input type="file" name="photo" class="input-file" accept="image/*" id="id_photo"
                           onchange="document.getElementById('upload-file-info').innerText = this.value;
                           document.getElementById('avatar').src = '';">
                    <br>
                    <span class='label-info' id="upload-file-info">Текущее фото: {{ form.photo.value }}</span>
                    {{ form.photo.errors }}
                </p>

            </div>

            <div id="contact">
                <input type="submit" class="save_button" value="Сохранить">
            </div>

        </div>
    </form>
{% endblock %}

lab3/people/templates/people/teacher_create.html
{% extends 'base.html' %}

{% block title %}Новый преподаватель{% endblock %}

{% block content %}
    <h1>Новый преподаватель</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        <div class="create-form">
            {% csrf_token %}
            <div id="left-side">
                <p>
                    {{ form.username }}
                    {{ form.username.errors }}
                </p>

                <p>
                    {{ form.email }}
                    {{ form.email.errors }}
                </p>

                <p>
                    {{ form.password }}
                    {{ form.password.errors }}
                </p>

                <p>
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </p>
                <p>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </p>

                <p>
                    <label for="{{ form.birth_date.id_for_label }}">Дата рождения:</label> <br>
                    {{ form.birth_date }}
                    {{ form.birth_date.errors }}
                </p>

                 <p>
                    <label for="{{ form.sex.id_for_label }}">Пол:</label> <br>
                    {{ form.sex }}
                    {{ form.sex.errors }}
                </p>
            </div>

            <div id="right-side">
                <p>
                    {{ form.description }}
                    {{ form.description.errors }}
                </p>
                <p>
                    {{ teacher_form.position }}
                    {{ teacher_form.position.errors }}
                </p>
                <p style="color: #606479; font-size: 14px">Фотография преподавателя:</p>
                <p>
                    <label class="label-file" for="{{ form.photo.id_for_label }}">Загрузить фото</label> <br>
                    <input type="file" name="photo" class="input-file" accept="image/*" id="id_photo"
                           onchange="document.getElementById('upload-file-info').innerText = this.value;">
                    <br>
                    <span class='label-info' id="upload-file-info"></span>
                    {{ form.photo.errors }}
                </p>
                <p>
                    <label for="{{ teacher_form.group_manager.id_for_label }}">Куратор группы:</label> <br>
                    {{ teacher_form.group_manager }}
                    {{ teacher_form.group_manager.errors }}
                </p>
                <p>
                    <label for="{{ teacher_form.lessons.id_for_label }}">Ведет предметы:</label> <br>
                    {{ teacher_form.lessons }}
                    {{ teacher_form.lessons.errors }}
                </p>
            </div>

            <div id="contact">
                <input type="submit" class="save_button" value="Сохранить">
            </div>

        </div>
    </form>
{% endblock %}

lab3/people/templates/people/teacher_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Список преподавателей{% endblock %}

{% block content %}
    <h1>Преподаватели</h1>
    <a class="btn btn-success" href="{% url 'teacher_add' %}">+ Добавить преподавателя</a>
    <table class="table-journal">
        <thead>
            <tr>
                <th>№</th>
                <th>Фото</th>
                <th>ФИО</th>
                <th>Должность</th>
                <th>Куратор</th>
                <th>Редактировать</th>
            </tr>
        </thead>
        <tbody>
            {% for user in user_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><img class="user-avatar-mini" src="/static/{{ user.photo }}" alt=""></td>
                    <td>
                        <a href="{{ user.teacher.get_absolute_url }}">
                            {{ user.get_full_name }}
                        </a>
                    </td>
                    <td>{{ user.teacher.position }}</td>
                    <td>
                        <a href="{{ user.teacher.group_manager.get_absolute_url }}">{{ user.teacher.group_manager }}</a>
                    </td>
                    <td>
                        <a class="btn btn-dark" href="{% url 'teacher_update' user.id %}">Редактировать</a>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}

lab3/people/templates/people/teacher_sidebar.html
{% block sidebar %}
    <h3>Личный кабинет</h3>
    <img class="user-avatar" src="/static/{{ user.photo }}" alt="{{ user.first_name }} {{ user.last_name }}">
    <p><b>{{ user.last_name }} {{ user.first_name }} </b></p>
    <hr>
    <ul>
        <li><a href="{% url 'group_student_list' %}">Журналы по учебным группам</a></li>
        <li><a href="{% url 'teacher_list' %}">Преподаватели</a></li>
        <li><a href="{% url 'mailing_list' %}">Рассылки</a></li>
    </ul>
    <hr>
    <p><b>Настройки:</b></p>
    <ul>
        <li><a href="{% url 'logout' %}">Выйти</a></li>
    </ul>
{% endblock %}

lab3/people/templates/people/teacher_update.html
{% extends 'base.html' %}

{% block title %}Редактировать преподавателя{% endblock %}

{% block content %}
    <h1>Редактировать преподавателя</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}

     <form action="" method="post" enctype="multipart/form-data">
        <div class="create-form">
            {% csrf_token %}

            <div id="left-side">

               <p>
                    <label for="{{ form.first_name.id_for_label }}">Имя:</label> <br>
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </p>
                <p>
                    <label for="{{ form.last_name.id_for_label }}">Фамилия:</label> <br>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </p>

                <p>
                    <label for="{{ form.birth_date.id_for_label }}">Дата рождения:</label> <br>
                    {{ form.birth_date }}
                    {{ form.birth_date.errors }}
                </p>

                 <p>
                    <label for="{{ form.sex.id_for_label }}">Пол:</label> <br>
                    {{ form.sex }}
                    {{ form.sex.errors }}
                </p>

                {{ teacher_form.management_form }}
                {{ teacher_form.as_p }}
            </div>

            <div id="right-side">
                <p>
                    <label for="{{ form.description.id_for_label }}">Характеристика:</label> <br>
                    {{ form.description }}
                    {{ form.description.errors }}
                </p>

                <p style="color: #606479; font-size: 14px">Фотография преподавателя:</p>
                <p>
                    <img id="avatar" align="left" class="user-avatar-mini" src="/media/{{ form.photo.value }}" alt="">
                    <label class="label-file" for="{{ form.photo.id_for_label }}">Загрузить фото</label> <br>
                    <input type="file" name="photo" class="input-file" accept="image/*" id="id_photo"
                           onchange="document.getElementById('upload-file-info').innerText = this.value;
                           document.getElementById('avatar').src = '';">
                    <br>
                    <span class='label-info' id="upload-file-info">Текущее фото: {{ form.photo.value }}</span>
                    {{ form.photo.errors }}
                </p>

            </div>

            <div id="contact">
                <input type="submit" class="save_button" value="Сохранить">
            </div>

        </div>
    </form>
{% endblock %}